export const enum ENTRIES {
  GROCERIES = "GROCERIES",
  WINERIES_SINGLE_APPROVAL = "WINERIES_SINGLE_APPROVAL",
  WINERIES = "WINERIES",
  HOTELS = "HOTELS",
  ZIMERS = "ZIMERS",
  PUBS = "PUBS",
  RESTAURANTS = "RESTAURANTS",
  COFFEE_SHOPS = "COFFEE_SHOPS",
  ICECREAM_SHOPS = "ICECREAM_SHOPS",
  PRESENT_PACKAGES = "PRESENT_PACKAGES",
  WINE_PACKAGES = "WINE_PACKAGES"
}


export const enum PAGE_MENU_ENTRIES {
  PRESENT_PACKAGES = "PRESENT_PACKAGES",
  WINE_PACKAGES = "WINE_PACKAGES",
  RESTAURANTS = "RESTAURANTS",
  COFFEE_SHOPS = "COFFEE_SHOPS",
  PUBS = "PUBS"
}

export const enum ITEM_ATTRIBUTES {
  SINGLE_APPROVAL = "SINGLE_APPROVAL",
  NO_APPROVAL = "NO_APPROVAL",
  NOT_QUALIFIED = "NOT_QUALIFIED",
  OPEN_SATURDAY = "OPEN_SATURDAY",
  WARNING = "WARNING"
}