export const enum ENTRIES {
  GROCERIES = "GROCERIES",
  WINERIES = "WINERIES",
  SERVICES = "SERVICES"
}

export const enum PAGE_MENU_ENTRIES {
  HOTELS = "HOTELS",
  PUBS = "PUBS",
  RESTAURANTS = "RESTAURANTS",
  PRESENT_PACKAGES = "PRESENT_PACKAGES",
  WINE_PACKAGES = "WINE_PACKAGES"
}

export const enum ITEM_ATTRIBUTES {
  SINGLE_APPROVAL = "SINGLE_APPROVAL",
  NO_APPROVAL = "NO_APPROVAL",
  NOT_QUALIFIED = "NOT_QUALIFIED",
  OPEN_SATURDAY = "OPEN_SATURDAY",
  WARNING = "WARNING"
}